aqua blog post script
awslabs/amazon-redshift-utils pull request #593
Opened 2022-01-05 21:13 UTC by happycontribute

*Description of changes:*
I am trying to put scripts for AQUA blog post in DB Eng repository and refer it in my blogpost. Public and Customer can follow blogpost and use scripts from this public repository 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-05 21:25 UTC, sgromoll requested changes
Please cleanup formatting a bit.

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_capture_query.sh
> +
Remove extra space

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_capture_query.sh
> +#"If user doesn't provide start and endtime, default to current time as start time and use queries from first 3 hours."
Clean up quotes/spacing

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +
Remove extra space

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +#TODO: Validate ALL inputs as shown below
Remove todo or implement.

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +#log execution startime
Is there a reason there is no indentation for these scripts?  Can you properly indent for readability?

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +#execute in redhshift three times
typo

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +echo "Please check the sql_error.log for erros, once SQL error's fixed and then re-run aqua_execute_query.sh"
typo

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +echo "Please check the sql_error.log for erros, once SQL error's fixed and then  re-run aqua_execute_query.sh"
typo

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +rm -f  capture_tmp.sql
extra space

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +
replace with two newlines.

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +
remove blank line

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#TO: Validate ALL connection  inputs
Implement or remove.

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +export  PGPASSWORD=$PGPASSWORD
remove extra space

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +
reduce to 1 newline

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#echo $RUNTIMEQUERY
remove if not needed

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#echo $X
remove if not needed

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#echo $BOOST_MIN_RUNTIME
remove if not needed.

2022-01-05 21:25 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +echo " The set of queries executed took $X in RedShift and took $Y in AQUA+RS.  The  performance gain AQUA for Redshift provided ranges from $BOOST_MIN_RUNTIME  to $BOOST_MAX_RUNTIME"
extra spaces

2022-01-14 06:13 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_capture_query.sh
> +
done

2022-01-14 06:13 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_capture_query.sh
> +#"If user doesn't provide start and endtime, default to current time as start time and use queries from first 3 hours."
cleaned it

2022-01-14 06:13 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_execute_query.sh
> +
removed

2022-01-14 06:13 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#echo $RUNTIMEQUERY
removed

2022-01-14 06:14 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +#echo $X
removed

2022-01-14 06:14 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +echo " The set of queries executed took $X in RedShift and took $Y in AQUA+RS.  The  performance gain AQUA for Redshift provided ranges from $BOOST_MIN_RUNTIME  to $BOOST_MAX_RUNTIME"
cleared spaces

2022-01-14 06:18 UTC, happycontribute commented on src/BlogContent/AQUA-Evaluation/aqua_perf_compare.sh
> +
removed spaces

2022-01-21 17:16 UTC, happycontribute commented
Please take a look at the readme file added and IP address are mocked in sample runs.

2022-01-28 22:22 UTC, sgromoll requested changes

2022-01-28 22:22 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/Aqua_eligible_testqueries.sql
> + SELECT customer_id , product_title , review_id  FROM amazon_reviews  WHERE product_title  SIMILAR TO ‘L%’ ORDER BY customer_id  LIMIT 20;
any reason there is inconsistent leading spaces and capitalization?   can we standard this throughout the file?  looks messy.

2022-01-28 22:22 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/Aqua_eligible_testqueries.sql
> +product_title SIMILAR TO  '%iph%' or
two spaces here... this all looks haphazard, can you clean up formatting please.

2022-01-28 22:22 UTC, sgromoll commented on src/BlogContent/AQUA-Evaluation/aqua_eligible_queries.sql
> +SELECT customer_id , product_title FROM amazon_reviews WHERE review_body SIMILAR TO '%(good|bad)%';; SELECT customer_id , product_title FROM amazon_reviews WHERE review_body SIMILAR TO '%(good|bad)%'
double ;;?

2022-02-03 00:30 UTC, merged